// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Task struct {
	ID          int32        `json:"id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Completed   sql.NullBool `json:"completed"`
}
